##################################################################
## 
##      Configuración del módulo pygeonica  
##      
##################################################################

Estaciones Operativas: 
    - 316
    - 2169

Servidor:
    IP: 138.4.46.69     # IP PC Ruben: '138.4.46.139'      IP PC Server: '138.4.46.69'
    Puerto: 49172       # Puerto por defecto del Servidor SQL que genera Geonica
    
BBDD:   # Valores por defecto de la base de datos Geonica
    Nombre: MeteoStation4k    
    Usuario: Geonica
    Contrasena: g30n1c4
    Database: GEONICASUITE4  K

Estacion: # Configuración necesaria parae estacion.py del módulo
    BYTEORDER : big
    PASS : "geonica "
    NUMERO_USUARIO : 1
    PORT : 30000
    TIEMPO_RTS_ACTIVO : 0.1
    TIEMPO_ESPERA_DATOS : 0.5   # Timepo de espera entre el envío de una trama y la escucha de la respuesta de la estación. Tener CUIDADO, valores bajos pueden imposibilitar la conexión.
    Estaciones:
        -
            Num: 316
            IP: 138.4.46.34
        -
            Num: 2169
            IP: 138.4.46.2
        -
            Num: 2171
            IP: 138.4.46.83

File: # Configuración sobre el fichero generado con la info de los sensores
    Nombre: meteo
    Path: "D:/datos/Datos Meteo IES/"

Tipo_Lectura_Canales: # Previamente deben de existir en la BBDD (por lo que deben de estar configuradas en Teletrans) - Medidas Instantáneas: Ins., Promedios: Med, Acumulado: Acu, OR Lógica...
    316:
        "Temp. Ai 1": Med
        "R.Directa1": Med
        "PIRAN.1": Med
        "PIRAN.2": Med
        "Celula Top": Med
        "Celula Mid": Med
        "Celula Bot": Med
        "Top - Cal ": Ins.
        "Mid - Cal ": Ins.
        "Bot - Cal ": Ins.
        "Presion": Med
        "V.Vien.1": Med
        "D.Vien.1": Med
        "Bateria": Med
        "Elev.Sol": Ins.
        "Orient.Sol": Ins.
        "Est.Geo3K": OR Lógica
        
    2169:
        "Temp. Ai 2": Med
        "Hum. Rel": Med
        "R.Directa2": Med
        "PIRAN.3": Med
        "PIRAN.4": Med
        "R.Infr.Inc": Med
        "VRef Ext.": Med
        "T.Carcasa": Med
        "Auxil.01": Med
        "V.Vien.2": Med
        "D.Vien.2": Med
        "Lluvia": Acu
        "Estado": OR Lógica
        "Elev.Sol": Ins.
        "Orient.Sol": Ins.
        "Est.Geo3K": OR Lógica
        
Dict_Rename: # Diccionario con los nombres de las variables que se desean modificar. Nombre en la estacion: Nombre que se desea que tenga la variable en el fichero generado
    "Estado" : Limpieza
    "PIRAN.1" : Gh                  # Global Horizontal
    "PIRAN.2" : Dh                  # Difusa Horizontal
    "PIRAN.3" : G(41)               # Global 41ยบ
    "PIRAN.4" : Gn                  # Global Normal
    "R.Directa1" : Bn               # Directa Normal
    "R.Directa2" : Bn_2             # Directa Normal 2
    "R.Infr.Inc" : Pirgeo           # Pirgeometro
    "T.Carcasa" : Temp_Pirgeo       # Temperatura Carcasa Pirgeometro
    
Vars_Excluidas: # Lista con las variables que se van a excluir del fihero generado
    - VRef Ext.
    - Bateria
    - Est.Geo3K