######################
##  IMPORTANTE:
##      
##      El separador decimal debe ser el punto '.'
##      Si en el valor hay algo mas aparte de un número, se intepretará como un string de caracteres.
##      En el caso de que haya una casilla vacía, se le asignará el valor None.
##
######################

Sensores:
    -
        Info:
            Marca: KIP & ZONEN
            Modelo: CM11
            NumSerie: CM11882151
            Tipo: Piranometro
        NumEstacion:
        NumCanal_Logico:
        NumCanal_Fisico:
        Nombre_Parametro:
        Configuracion:
            Sensibilidad: 4.89
            Sensibilidad_unidad:  uV(W/m2)
            Constante: 204,498977
            Funcion_Matematica:
        Etiqueta: Pirano
        Comentarios: No conectado desde 2020-03, antiguo D(0) en Helios. Sustituido por Eppley 18565F3
    -
        Info:
            Marca: YOUNG
            Modelo:
            NumSerie:
            Tipo: Sonda Temp
        NumEstacion: 316
        NumCanal_Logico: 1
        NumCanal_Fisico: A01
        Nombre_Parametro: Temp. Ai 1
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad: 
            Constante: 1
            Funcion_Matematica: YSI44031
        Etiqueta: Temp
        Comentarios:
    -
        Info:
            Marca: EPPLEY
            Modelo: NIP
            NumSerie: 3452E6
            Tipo: Pirheliometro
        NumEstacion: 316
        NumCanal_Logico: 2
        NumCanal_Fisico: A02
        Nombre_Parametro: R.Directa1
        Configuracion:
            Sensibilidad: 7.79
            Sensibilidad_unidad: uV(W/m2)
            Constante: 128.5347
            Funcion_Matematica:
        Etiqueta: Datos Seg
        Comentarios:
    -
        Info:
            Marca: EPPLEY
            Modelo: PSP
            NumSerie: 15426F3
            Tipo: Piranometro
        NumEstacion: 316
        NumCanal_Logico: 3
        NumCanal_Fisico: A03
        Nombre_Parametro: PIRAN.1
        Configuracion:
            Sensibilidad: 7.85
            Sensibilidad_unidad: uV(W/m2)
            Constante: 127.3885
            Funcion_Matematica:
        Etiqueta: Pirano 1
        Comentarios:
    -
        Info:
            Marca: EPPLEY
            Modelo: PSP
            NumSerie: 18565F3
            Tipo: Piranometro
        NumEstacion: 316
        NumCanal_Logico: 4
        NumCanal_Fisico: A04
        Nombre_Parametro: PIRAN.2
        Configuracion:
            Sensibilidad: 8.92
            Sensibilidad_unidad: uV(W/m2)
            Constante: 112.1076
            Funcion_Matematica:
        Etiqueta: Pirano 2
        Comentarios: Anteriormente instalado en seguidor módulos para GNI (controlado por Steve)
    -
        Info:
            Marca:
            Modelo:
            NumSerie:
            Tipo:
        NumEstacion: 316
        NumCanal_Logico: 5, 6, 7
        NumCanal_Fisico: A05, A06, A07
        Nombre_Parametro: Celula Top, Celula Mid, Celula Bot
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad: uV(W/m2)
            Constante: 13.4479, 13.22984, 15.67062
            Funcion_Matematica:
        Etiqueta: TRIT REF
        Comentarios:
    -
        Info:
            Marca: YOUNG
            Modelo: 61302L
            NumSerie: BP21143
            Tipo: Barometro
        NumEstacion: 316
        NumCanal_Logico: 11
        NumCanal_Fisico: A11
        Nombre_Parametro: Presion
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad:
            Constante:
            Funcion_Matematica:
        Etiqueta: Pt ATM
        Comentarios:
    -
        Info:
            Marca: WINDSONIC
            Modelo:
            NumSerie: CM11882151
            Tipo: Anemometro
        NumEstacion: 316
        NumCanal_Logico: 12, 13
        NumCanal_Fisico: 
        Nombre_Parametro: V.Vien.1, D.Vien.1
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad:
            Constante:
            Funcion_Matematica:
        Etiqueta: Viento VEL_DIR
        Comentarios:
    -
        Info:
            Marca: GEONICA
            Modelo:
            NumSerie:
            Tipo: Sonda Temp+RH
        NumEstacion: 2169
        NumCanal_Logico: 1, 2
        NumCanal_Fisico: A01, A02
        Nombre_Parametro: Temp. Ai 2, Hum. Rel
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad:
            Constante:
            Funcion_Matematica: YSI44031
        Etiqueta: T.amb + RH
        Comentarios:
    -
        Info:
            Marca: KIPP & ZONEN
            Modelo: CH1 NIP
            NumSerie: CH11930035
            Tipo: Pirheliometro
        NumEstacion:
        NumCanal_Logico:
        NumCanal_Fisico:
        Nombre_Parametro:
        Configuracion:
            Sensibilidad: 7.63
            Sensibilidad_unidad: uV(W/m2)
            Constante: 131.0615989
            Funcion_Matematica:
        Etiqueta:
        Comentarios: Desconectado en 2020-03. Se cambia por K&Z CHP1
    -
        Info:
            Marca: KIPP & ZONEN
            Modelo: CHP1
            NumSerie: 110753
            Tipo: Pirheliometro
        NumEstacion: 2169
        NumCanal_Logico: 3
        NumCanal_Fisico: A03
        Nombre_Parametro: R.Directa2
        Configuracion:
            Sensibilidad: 7.75
            Sensibilidad_unidad: uV(W/m2)
            Constante: 129.0323
            Funcion_Matematica:
        Etiqueta: Pirhelio K&Z
        Comentarios: Anteriomente usado por III-V.
    -
        Info:
            Marca: EPPLEY
            Modelo: PSP
            NumSerie: 18564F3
            Tipo: Piranometro
        NumEstacion: 2169
        NumCanal_Logico: 4
        NumCanal_Fisico: A04
        Nombre_Parametro: PIRAN.3
        Configuracion:
            Sensibilidad: 7.82
            Sensibilidad_unidad: uV(W/m2)
            Constante: 127.8772378
            Funcion_Matematica:
        Etiqueta: Pirano 3
        Comentarios:
    -
        Info:
            Marca: LI-COR
            Modelo: LI-2000
            NumSerie: PY74650
            Tipo: Piranometro
        NumEstacion: 2169
        NumCanal_Logico: 5
        NumCanal_Fisico: A08
        Nombre_Parametro: PIRAN.4
        Configuracion:
            Sensibilidad: 76.45
            Sensibilidad_unidad: (W/m2)/mV
            Constante: 76.45
            Funcion_Matematica:
        Etiqueta: Pirano 4(Corriente)
        Comentarios:
    -
        Info:
            Marca: KIPP & ZONEN
            Modelo: CGR3
            NumSerie: 190440
            Tipo: Pirgeometro
        NumEstacion: 2169
        NumCanal_Logico: 6, 8
        NumCanal_Fisico: A05, A06
        Nombre_Parametro: R.Infr.Inc, T.Carcasa
        Configuracion:
            Sensibilidad: 13.3
            Sensibilidad_unidad: uV(W/m2)
            Constante: 75.1879699
            Funcion_Matematica:
        Etiqueta: Pirgeometro
        Comentarios:
    -
        Info:
            Marca: WINDSONIC
            Modelo:
            NumSerie:
            Tipo: Anemometro
        NumEstacion: 2169
        NumCanal_Logico: 10, 11
        NumCanal_Fisico:
        Nombre_Parametro: V.Vien.2, D.Vien.2
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad:
            Constante:
            Funcion_Matematica:
        Etiqueta: Viento VEL_DIR
        Comentarios:
    -
        Info:
            Marca: PRONAMIC
            Modelo: DK-8600
            NumSerie:
            Tipo: Pluviometro
        NumEstacion: 2169
        NumCanal_Logico: 12
        NumCanal_Fisico: CP1B
        Nombre_Parametro: Lluvia
        Configuracion:
            Sensibilidad:
            Sensibilidad_unidad:
            Constante:
            Funcion_Matematica:
        Etiqueta: Pluviometro
        Comentarios: